# Generated by Django 4.0.3 on 2022-03-12 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kla_connect_utils.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kla_connect_location', '0002_alter_area_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KlaConnectIncidentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KlaConnectIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('priority', models.IntegerField(choices=[(1, 'Emergency'), (2, 'Non-Emergency')])),
                ('subject', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='attachments/%Y/%m/%d')),
                ('ref', models.CharField(default=kla_connect_utils.helpers.generate_ref_number, max_length=10, unique=True)),
                ('feedback', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='pending', max_length=25)),
                ('affected_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kla_connect_location.area')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kla_connect_incidents.klaconnectincidenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
