# Generated by Django 4.0.3 on 2022-03-12 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_location', '0003_alter_area_parent'),
        ('kla_connect_incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaconnectincident',
            name='affected_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kla_connect_location.area'),
        ),
    ]
