# Generated by Django 4.0.3 on 2022-03-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_incidents', '0002_alter_klaconnectincident_affected_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='klaconnectincidenttype',
            name='show_icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/%Y/%m/%d'),
        ),
    ]
