# Generated by Django 4.0.3 on 2022-03-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_incidents', '0003_klaconnectincidenttype_show_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klaconnectincident',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='klaconnectincidenttype',
            options={'ordering': ['created_on']},
        ),
    ]
