# Generated by Django 4.0.3 on 2022-03-14 11:29

from django.db import migrations, models
import kla_connect_utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_incidents', '0004_alter_klaconnectincident_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaconnectincident',
            name='ref',
            field=models.CharField(default=kla_connect_utils.helpers.generate_ref_number, max_length=20, unique=True),
        ),
    ]
