# Generated by Django 4.0.3 on 2022-03-15 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kla_connect_utils.helpers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kla_connect_location', '0004_alter_area_options'),
        ('kla_connect_incidents', '0005_alter_klaconnectincident_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlaConnectReportType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KlaConnectReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=225)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='attachments/%Y/%m/%d')),
                ('ref', models.CharField(default=kla_connect_utils.helpers.generate_rep_ref_number, max_length=20, unique=True)),
                ('feedback', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='pending', max_length=25)),
                ('affected_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kla_connect_location.area')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kla_connect_incidents.klaconnectreporttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
    ]
