# Generated by Django 4.0.3 on 2022-03-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_incidents', '0006_klaconnectreporttype_klaconnectreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klaconnectincident',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='klaconnectincidenttype',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='klaconnectreport',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='klaconnectreporttype',
            options={'ordering': ['-created_on']},
        ),
    ]
