# Generated by Django 4.0.3 on 2022-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_incidents', '0009_reportview_reportlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaconnectincident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='klaconnectincident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
    ]
