# Generated by Django 4.0.3 on 2022-03-28 16:42

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_incidents', '0010_alter_klaconnectincident_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaconnectincident',
            name='attachment',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=60, size=[500, 300], upload_to='attachments/incidents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='klaconnectreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/reports/%Y/%m/%d'),
        ),
    ]
