# Generated by Django 4.0.3 on 2022-03-28 16:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_incidents', '0011_alter_klaconnectincident_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaconnectincident',
            name='attachment',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='attachments/incidents/%Y/%m/%d'),
        ),
    ]
