# Generated by Django 4.0.3 on 2022-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_incidents', '0012_alter_klaconnectincident_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaconnectincident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('for_review', 'For Review'), ('complete', 'Approved')], default='pending', max_length=25),
        ),
    ]
