# Generated by Django 4.0.3 on 2022-03-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaconnectuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
