# Generated by Django 4.0.3 on 2022-03-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_auth', '0002_alter_klaconnectuser_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['created_on']},
        ),
    ]
