# Generated by Django 4.0.3 on 2022-03-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_auth', '0003_alter_loginattempt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klaconnectuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-created_on']},
        ),
    ]
