# Generated by Django 4.0.3 on 2022-03-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='klaconnectuserprofile',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='profilevalidation',
            options={'ordering': ['created_on']},
        ),
    ]
