# Generated by Django 4.0.3 on 2022-03-16 15:30

from django.db import migrations, models
import django.db.models.deletion
import kla_connect_utils.helpers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_profiles', '0002_alter_department_options_alter_designation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlaConnectLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='klaconnectuserprofile',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='profilevalidation',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='profilevalidation',
            name='code',
            field=models.CharField(default=kla_connect_utils.helpers.generate_verification_code, max_length=5, unique=True),
        ),
        migrations.CreateModel(
            name='KlaConnectLanguageWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=30)),
                ('word', models.CharField(max_length=30)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_words', to='kla_connect_profiles.klaconnectlanguage')),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='klaconnectuserprofile',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kla_connect_profiles.klaconnectlanguage'),
        ),
    ]
