# Generated by Django 4.0.3 on 2022-04-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_profiles', '0004_alter_klaconnectuserprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaconnectuserprofile',
            name='nationality',
            field=models.IntegerField(blank=True, choices=[(1, 'Ugandan'), (0, 'Non Uganda')], null=True),
        ),
    ]
