# Generated by Django 4.0.3 on 2022-04-19 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kla_connect_profiles', '0005_alter_klaconnectuserprofile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaconnectuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
