# Generated by Django 4.0.3 on 2022-03-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_location', '0003_alter_area_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['created_on']},
        ),
    ]
