# Generated by Django 4.0.3 on 2022-03-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kla_connect_location', '0004_alter_area_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-created_on']},
        ),
    ]
